### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by azu** [textlint/textlint-scripts#27]
We want to support TypeScript

**Comment by robertobatts** [comment]
Hi, what do you want to do with typescript exactly?

**Comment by azu** [comment]
Currently, `textlint-scripts build` and `textlint-scripts test` does not handle `*.ts` file.
Internally, `textlint-script` use Babel. So, we can support `*.ts` file with [@babel/preset-typescript](https://babeljs.io/docs/en/babel-preset-typescript).
(textlint is already written in TypeScript)

Of course, We need to create/update https://github.com/textlint/textlint-rule-template for TypeScript.

Similar approach is [Adding TypeScript · Create React App](https://facebook.github.io/create-react-app/docs/adding-typescript).

**Comment by azu** [comment]
resolved by #33
